 steps:
    # Update pip in vm
    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'pip', 'install', '--upgrade', 'pip']
    # Install dependencies in vm
    # - name: python
    #   entrypoint: pip
    #   args: ["install", "-r", "requirements.txt", "--user"]
    # Deploy to cloudrun
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
      - gcloud
      - functions
      - deploy
      - dip-backend-functions
      - --region=asia-southeast2	
      - --source=.
      - --trigger-http
      - --runtime=RUNTIME
